### ISSUE TITLE
let Typescript infer types

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#12]
https://github.com/baseplate-admin/CoreProject-V3-UI/blob/8a6185c7a9d2267634e1b616be9133dea6aadfd4/src/lib/components/shared/ScrollArea.svelte#L4-L12

**Comment by baseplate-admin** [comment]
> Problem with :string types only?

All infered types. VSCode throws errors

**Comment by sssuneeth** [comment]
> All infered types. VSCode throws errors

So I need to remove all types?
Like what type of errors?

**Comment by baseplate-admin** [comment]
>  But I question is does this problem happens with :number and :boolean too?

Yep
