### ISSUE TITLE
Spacing is not right

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#14]
![image](https://user-images.githubusercontent.com/61817579/232090039-96a32afa-7812-4b8f-80e9-96553eea040f.png)

you have to use VW/VH

**Comment by sssuneeth** [comment]
> you have to use VW/VH

I used vw for items width and height
Forgot to add on icons and spacing, I think

Yea will do it

**Comment by sssuneeth** [comment]
@baseplate-admin 
I updated sidebar and header
check now
https://github.com/baseplate-admin/CoreProject-V3-UI/commit/c32f633c346d72855e552fc2b765c0d1d667ec79

**Comment by baseplate-admin** [comment]
Not a big fan of it tbh. I would have rather liked if you used `margin` with `vw`

**Comment by baseplate-admin** [comment]
![image](https://user-images.githubusercontent.com/61817579/232246037-5b8840a5-01ae-411d-80c0-ae9c63cb4e08.png)


Not looking the best on my screen `1920x1080`

**Comment by sssuneeth** [comment]
> Not a big fan of it tbh. I would have rather liked it if you used margin with vw

Yea, `margin-top` with `vw` will do the same job, Idk why you hate `justify-between`.

**Comment by baseplate-admin** [comment]
> Idk why you hate justify-between.

Not a fan of undefined Heights

**Comment by sssuneeth** [comment]
@baseplate-admin 

Take a look now https://v3.coreproject.moe/

**Comment by baseplate-admin** [comment]
I need to modify it myself.

**Comment by sssuneeth** [comment]
> I need to modify it myself

What now? Isnt it looking good?
