### ISSUE TITLE
Add glass effect

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#15]
![Screenshot from 2023-04-14 22-43-26](https://user-images.githubusercontent.com/61817579/232105901-7561e31c-de6d-4408-b0fc-27e54c6711dd.png)

**Comment by sssuneeth** [comment]
> Add glass effect

Something like `backdrop-blur`?
https://tailwindcss.com/docs/backdrop-blur#blurring-behind-an-element

**Comment by baseplate-admin** [comment]
Something like 
![image](https://user-images.githubusercontent.com/61817579/232106736-e6ffc89b-2bf4-4377-b519-a8f7bcde92fa.png)


From https://www.skeleton.dev/docs/themes

**Comment by baseplate-admin** [comment]
@sssuneeth,

I meant this one https://www.skeleton.dev/docs/variants#glass

**Comment by sssuneeth** [comment]
![Screenshot from 2023-04-14 23-37-48](https://user-images.githubusercontent.com/114811070/232123478-d743bb74-f933-4753-9829-49f7922d9f33.png)

Oky, take a look now
Is it okay? used `variant-glass-tertiary`

**Comment by baseplate-admin** [comment]
Alright forget this. I need to look into it
