### ISSUE TITLE
Fix spacing on this component

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#16]
![Screenshot from 2023-04-14 22-43-12](https://user-images.githubusercontent.com/61817579/232106013-639cc566-630d-4965-b757-c4211d23118d.png)

**Comment by sssuneeth** [comment]
> Fix spacing on this component

Huh! where? In that rating star section?

**Comment by baseplate-admin** [comment]
![Screenshot from 2023-04-14 22-50-55](https://user-images.githubusercontent.com/61817579/232107506-4b5ca1b8-bba4-4c00-b590-d43deffed55f.png)
![Screenshot from 2023-04-14 22-51-07](https://user-images.githubusercontent.com/61817579/232107513-cfb03016-f74f-490d-99af-5dc1e4db5f69.png)


Do you see any problems?
