### ISSUE TITLE
Fix button

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#17]
![image](https://user-images.githubusercontent.com/61817579/232106325-1a0b66f2-30fb-4652-a095-fa39472c7c77.png)

**Comment by sssuneeth** [comment]
Can you provide a little bit wider image?
I cant find its location

**Comment by baseplate-admin** [comment]
https://www.figma.com/file/tNUUtsk20ltOrQICdEoggG/Core-Project?node-id=1875-2336&t=da5oW2hfAaBKmg02-0

**Comment by sssuneeth** [comment]
Seems like I cant find that buttons background matching color
Its bg-color is `#1E2036` and there is no color in `theme.scss` like this or almost same

`bg-surface-500` seems good, but little darker

**Comment by baseplate-admin** [comment]
![Uploading image.png…]()

Works flawlessly
