### ISSUE TITLE
Button is not Clickable

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#19]
![image](https://user-images.githubusercontent.com/61817579/232120057-0a521e8d-bad6-48c4-918b-d9c8db45fdda.png)

This button is not clickable

**Comment by sssuneeth** [comment]
> This button is not clickable

Its working fine on my screen and with your screen resolutions (`Ctrl + Shift + M`)

**Comment by baseplate-admin** [comment]
Its missing btn class

**Comment by baseplate-admin** [comment]
Theres no animation

**Comment by sssuneeth** [comment]
> Its missing btn class

Yea, but it has `btn-icon` class

>Theres no animation

In my screen it has nice animations like others
Oky I can replace it with `btn` if you want, I tried it NP

**Comment by baseplate-admin** [comment]
> In my screen it has nice animations like others

What?
