### ISSUE TITLE
These icons look small

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#21]
![image](https://user-images.githubusercontent.com/61817579/232237894-9031ae92-d325-4d81-990a-b682ee5eefb9.png)

**Comment by sssuneeth** [comment]
No way? It was same size as in the design

**Comment by baseplate-admin** [comment]
> No way? It was same size as in the design

make it bit larger

**Comment by baseplate-admin** [comment]
[Screencast from 2023-04-15 22-32-20.webm](https://user-images.githubusercontent.com/61817579/232238179-e8f2c719-7e40-4f36-b85a-36afb962d1fb.webm)


Also these buttons have this weird thing going on

**Comment by sssuneeth** [comment]
> Also these buttons have this weird thing going on

Every buttons with icons has this issue,  
I think it maybe some pixel ratio problems?

**Comment by baseplate-admin** [comment]
> Every buttons with icons has this issue,

I will see this later. Keep this issue open

**Comment by sssuneeth** [comment]
> I will see this later. Keep this issue open

Do I need to open a issue on skeleton?

**Comment by baseplate-admin** [comment]
> Do I need to open a issue on skeleton?

Leave it to me :)

**Comment by baseplate-admin** [comment]
I investigated. It seems a skeleton thing. Not mich we can do
