### ISSUE TITLE
Add `urls.ts` from main CoreProject

### ISSUE THREAD

**Issue by baseplate-admin** [baseplate-admin/CoreProject-V3-UI#24]
https://github.com/baseplate-admin/CoreProject/blob/22964e7a32be88114b416493036474b6e1bc9ebe/frontend/AnimeCore/src/lib/data/urls.ts

Add this file

**Comment by baseplate-admin** [comment]
Note that this file requires you to add loadsh as dependency

**Comment by sssuneeth** [comment]
> Add this file

Just need to add to data? or anything else?

> Note that this file requires you to add loadsh as dependency

Yea, will install that

**Comment by baseplate-admin** [comment]
> Just need to add to data? or anything else?

File contains our entire backend mapping
